---
- name: Setup Kubernetes on all Nodes
  hosts: all          # Runn script on both master and worker nodes
  become: yes
  tasks:
    - name: Copy the k8-ubuntu.sh script to remote nodes
      copy:
        src: ./k8-ubuntu.sh
        dest: /home/k8-ubuntu.sh
        mode: '0755'

    - name: Run the k8-ubuntu.sh script
      shell: /home/k8-ubuntu.sh
