---
- name: Setup Kubernetes on all Nodes
  hosts: all          # Runn script on both master and worker nodes
  become: yes
  tasks:
    - name: Copy the k8-ubuntu.sh script to remote nodes
      copy:
        src: ./k8-ubuntu.sh
        dest: /tmp/k8-ubuntu.sh
        mode: '0755'
##
    - name: Run the k8-ubuntu.sh script
      shell: bash /tmp/k8-ubuntu.sh  

    - name: Remove the k8-ubuntu.sh script after execution
      file:
        path: /tmp/k8-ubuntu.sh
        state: absent
